import fs from 'fs';
import path from 'path';

const detailsPath = path.join(process.cwd(), 'details.json');
const outPath = path.join(process.cwd(), 'mongo_bulk_updates.js');

const details = JSON.parse(fs.readFileSync(detailsPath, 'utf8'));

function oidObj(oid) {
  return `{ "$oid": "${oid}" }`;
}

const entries = details.map(d => {
  const categoriesStr = d.categories_id.map(c => `                        ${JSON.stringify(c)}`).join(',\n');
  const colorStr = d.color_id ? JSON.stringify(d.color_id) : 'null';

  return `    {
        updateOne: {
            filter: { id: ${d.id} },
            update: {
                $unset: { "category_id": "" },
                $set: {
                    "categories_id": [
${categoriesStr}
                    ],
                    "color_id": ${colorStr}
                }
            }
        }
    }`;
});

const fileContent = `// Generated by generate_bulk_write.js
// Paste the following into mongosh or run in MongoDB shell that accepts JS

db.products.bulkWrite([
${entries.join(',\n')}
]);
`;

fs.writeFileSync(outPath, fileContent, 'utf8');
console.log(`Wrote ${outPath} with ${details.length} updateOne entries.`);
