services:
  - type: web
    name: kltn-watch-store-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false  # This will be set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true  # Render will generate a random value
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        sync: false  # Set this after deploying frontend
      - key: ADMIN_URL
        sync: false  # Set this after deploying admin
